language: node_js

cache:
  directories:
    - node_modules

node_js:
  - "8.11"

install:
  - npm install

script:
  - npm test
  - npm run coverage
#  - coveralls < ./coverage/lcov.info || true # if coveralls doesn't have it covered

# Allow Travis tests to run in containers.
sudo: false

after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
