language: node_js

node_js:
  - "8.11"

install:
  - npm install

script:
  - npm test
#  - npm run coverage
#  - coveralls < ./coverage/lcov.info || true # if coveralls doesn't have it covered

# Allow Travis tests to run in containers.
sudo: false
